on: 
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
name: 🚀 FTP Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - run: |
        sh download.sh
        
    - name: 📂 Sync files         
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.tycho.ir
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        exclude: |
          **/.git*
          **/.git*/**
          **README.md**
